load("//:rules.bzl", "patched_tilesheet_asm")

patched_tilesheet_asm(
    name = "tilegfx1",
    manifest_csv = "manifest.csv",
    pngs = [
        "sample1.png",
        "sample2.png",
    ],
    rom = "lttp.sfc",
    sheet_num = 1,
)
